"""user.orders

Revision ID: e3dfe67867c9
Revises: ed366e5bfa4d
Create Date: 2022-07-03 17:07:46.301404

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3dfe67867c9'
down_revision = 'ed366e5bfa4d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
